//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseProject.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add collection.
        /// </summary>
        public static string Add_collection {
            get {
                return ResourceManager.GetString("Add collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string Add_item {
            get {
                return ResourceManager.GetString("Add item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item to.
        /// </summary>
        public static string Add_item_to {
            get {
                return ResourceManager.GetString("Add item to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new collection.
        /// </summary>
        public static string Add_new_collection {
            get {
                return ResourceManager.GetString("Add new collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added / Last changed:.
        /// </summary>
        public static string Added___Last_changed_ {
            get {
                return ResourceManager.GetString("Added / Last changed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin info.
        /// </summary>
        public static string Admin_info {
            get {
                return ResourceManager.GetString("Admin info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest collections.
        /// </summary>
        public static string Biggest_collections {
            get {
                return ResourceManager.GetString("Biggest collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool values count.
        /// </summary>
        public static string Bool_values_count {
            get {
                return ResourceManager.GetString("Bool values count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool.
        /// </summary>
        public static string BoolType {
            get {
                return ResourceManager.GetString("BoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date.
        /// </summary>
        public static string By_date {
            get {
                return ResourceManager.GetString("By date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date descending.
        /// </summary>
        public static string By_date_descending {
            get {
                return ResourceManager.GetString("By date descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By likes.
        /// </summary>
        public static string By_likes {
            get {
                return ResourceManager.GetString("By likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By likes descending.
        /// </summary>
        public static string By_likes_descending {
            get {
                return ResourceManager.GetString("By likes descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        public static string Change_role {
            get {
                return ResourceManager.GetString("Change role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection id.
        /// </summary>
        public static string Collection_id {
            get {
                return ResourceManager.GetString("Collection id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection picture.
        /// </summary>
        public static string Collection_picture {
            get {
                return ResourceManager.GetString("Collection picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment this item.
        /// </summary>
        public static string Comment_this_item {
            get {
                return ResourceManager.GetString("Comment this item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseProject.
        /// </summary>
        public static string CourseProject {
            get {
                return ResourceManager.GetString("CourseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime values count.
        /// </summary>
        public static string DateTime_values_count {
            get {
                return ResourceManager.GetString("DateTime values count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateType {
            get {
                return ResourceManager.GetString("DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete collection.
        /// </summary>
        public static string Delete_collection {
            get {
                return ResourceManager.GetString("Delete collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit collection.
        /// </summary>
        public static string Edit_collection {
            get {
                return ResourceManager.GetString("Edit collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string Edit_item {
            get {
                return ResourceManager.GetString("Edit item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Month / Day / Year Hour: Minute: Second PM/ AM.Time is optional.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int values count.
        /// </summary>
        public static string Int_values_count {
            get {
                return ResourceManager.GetString("Int values count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        public static string IntType {
            get {
                return ResourceManager.GetString("IntType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is admin.
        /// </summary>
        public static string Is_admin {
            get {
                return ResourceManager.GetString("Is admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is blocked.
        /// </summary>
        public static string Is_blocked {
            get {
                return ResourceManager.GetString("Is blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item from.
        /// </summary>
        public static string Item_from {
            get {
                return ResourceManager.GetString("Item from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Count.
        /// </summary>
        public static string Items_Count {
            get {
                return ResourceManager.GetString("Items Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items settings.
        /// </summary>
        public static string Items_settings {
            get {
                return ResourceManager.GetString("Items settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last added items.
        /// </summary>
        public static string Last_added_items {
            get {
                return ResourceManager.GetString("Last added items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users.
        /// </summary>
        public static string List_of_users {
            get {
                return ResourceManager.GetString("List of users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look.
        /// </summary>
        public static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string Password_confirmation {
            get {
                return ResourceManager.GetString("Password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login.
        /// </summary>
        public static string Please_login {
            get {
                return ResourceManager.GetString("Please login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        public static string Results_for {
            get {
                return ResourceManager.GetString("Results for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send comment.
        /// </summary>
        public static string Send_comment {
            get {
                return ResourceManager.GetString("Send comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show collection.
        /// </summary>
        public static string Show_collection {
            get {
                return ResourceManager.GetString("Show collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item.
        /// </summary>
        public static string Show_item {
            get {
                return ResourceManager.GetString("Show item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String values count.
        /// </summary>
        public static string String_values_count {
            get {
                return ResourceManager.GetString("String values count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cloud.
        /// </summary>
        public static string Tag_cloud {
            get {
                return ResourceManager.GetString("Tag cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image for collection.
        /// </summary>
        public static string Upload_image_for_collection {
            get {
                return ResourceManager.GetString("Upload image for collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password or login.
        /// </summary>
        public static string Wrong_password_or_login {
            get {
                return ResourceManager.GetString("Wrong password or login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are blocked.
        /// </summary>
        public static string You_are_blocked {
            get {
                return ResourceManager.GetString("You are blocked", resourceCulture);
            }
        }
    }
}
